export default function Head() {
  return (
    <>
      <title>Spring Next.js Gcash Demo</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta
        name='description'
        content='Generated by Spring Next.js Gcash Demo'
      />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
