### Admin User
### Admin Login
POST {{address}}/login
Content-Type: application/json

{
  "username": "Raphile",
  "password": "123"
}

### Admin Register
POST {{address}}/register
Content-Type: application/json

{
  "username": "Raphile",
  "email": "rllddalangin@gmail.com",
  "password": "123"
}

### Guest User
### Guest Login
POST {{address}}/login
Content-Type: application/json

{
  "username": "Carry",
  "password": "123"
}

### Guest Register
POST {{address}}/register
Content-Type: application/json

{
  "username": "Carry",
  "email": "dalanginraphael@gmail.com",
  "password": "123"
}
