### User Login
POST {{address}}/login
Content-Type: application/json

{
  "username": "Raphile",
  "password": "123"
}

### User Register
POST {{address}}/register
Content-Type: application/json

{
  "username": "Raphile",
  "email": "rllddalangin@gmail.com",
  "password": "123"
}